# Generated by Django 3.0.5 on 2021-09-15 06:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicImageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ForensicImages')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('desc', models.TextField(default='No Description', max_length=100)),
                ('Phone', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaitentForensicAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('desc', models.TextField()),
                ('flie', models.FileField(upload_to='document')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 23, 49, 981455), null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForensicAppointmentRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ForensicAppointments')),
                ('desc', models.TextField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('forensic_agent_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 23, 49, 973425), null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseForPaitentDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('suggestions', models.TextField()),
                ('flie', models.FileField(upload_to='document')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 23, 49, 981455), null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDoctorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('report', models.FileField(upload_to='document')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 23, 49, 973425), null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
