# Generated by Django 3.2.7 on 2021-09-15 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdoctormodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 42, 2, 825582), null=True),
        ),
        migrations.AlterField(
            model_name='databaseforpaitentdoctor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 42, 2, 825582), null=True),
        ),
        migrations.AlterField(
            model_name='forensicappointmentrequests',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 42, 2, 824582), null=True),
        ),
        migrations.AlterField(
            model_name='paitentforensicappointment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 15, 11, 42, 2, 825582), null=True),
        ),
    ]
